import React from 'react';
import bgImg from '../assets/fifa_wc_bg_light.png';

const LeaderboardExportView = React.forwardRef(({ leaderboard }, ref) => {
  const top20 = leaderboard.slice(0, 20);

  const getRankIcon = (rank) => {
    if (rank === 1) return '🥇';
    if (rank === 2) return '🥈';
    if (rank === 3) return '🥉';
    return `#${rank}`;
  };

  return (
    <div
      ref={ref}
      style={{
        position: 'absolute',
        top: 0,
        left: '-9999px',
        width: '600px',
        backgroundImage: `url(${bgImg})`,
        backgroundSize: 'cover',
        backgroundPosition: 'center top',
        backgroundColor: '#f1f5f9',
        color: '#0f172a',
        padding: '32px',
        zIndex: -999, // Hides behind main content without opacity: 0
        pointerEvents: 'none',
        fontFamily: 'Inter, sans-serif'
      }}
      id="leaderboard-export-container"
    >
      {/* Header */}
      <div style={{ textAlign: 'center', marginBottom: '32px' }}>
        <h1 style={{ fontSize: '28px', fontWeight: 800, margin: '0 0 8px 0', background: 'linear-gradient(to right, #0d6efd, #8b5cf6)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
          GRAPHWHITE FIFA WORLD CUP '26
        </h1>
        <h2 style={{ fontSize: '18px', fontWeight: 600, color: '#475569', margin: 0 }}>
          Top 20 Leaderboard
        </h2>
      </div>

      {/* List */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        {top20.map((user, index) => (
          <div
            key={user.id}
            style={{
              display: 'flex',
              alignItems: 'center',
              background: index < 3 ? 'rgba(255, 255, 255, 0.95)' : 'rgba(255, 255, 255, 0.75)',
              borderRadius: '12px',
              padding: '12px 16px',
              boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
              borderLeft: index === 0 ? '4px solid #f59e0b' : index === 1 ? '4px solid #94a3b8' : index === 2 ? '4px solid #c2410c' : '4px solid transparent'
            }}
          >
            <div style={{ width: '40px', fontSize: '16px', fontWeight: 700, color: '#475569' }}>
              {getRankIcon(user.rank)}
            </div>

            {user.photoURL ? (
              <img
                src={user.photoURL}
                alt=""
                style={{ width: '32px', height: '32px', borderRadius: '50%', marginRight: '16px', objectFit: 'cover' }}
                crossOrigin="anonymous"
              />
            ) : (
              <div style={{ width: '32px', height: '32px', borderRadius: '50%', marginRight: '16px', background: 'rgba(0,0,0,0.1)' }}></div>
            )}

            <div style={{ flex: 1, fontSize: '16px', fontWeight: 600, color: '#0f172a' }}>
              {user.displayName}
            </div>

            <div style={{ fontSize: '18px', fontWeight: 800, color: '#0d6efd' }}>
              {user.totalPoints} <span style={{ fontSize: '12px', color: '#64748b', fontWeight: 600 }}>pts</span>
            </div>
          </div>
        ))}
      </div>

      {/* Footer Branding */}
      <div style={{ marginTop: '24px', textAlign: 'center', fontSize: '12px', color: '#475569', fontWeight: 500 }}>
        Generated by GraphWhite Predictor App • {new Date().toLocaleDateString()}
      </div>
    </div>
  );
});

export default LeaderboardExportView;
